# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import tabungan_berjangka, simulasi_peminjaman,anggaran_bulanan


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 200, 461, 151))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSimulasi_Tabungan_Berjangka = QtWidgets.QAction(MainWindow)
        self.actionSimulasi_Tabungan_Berjangka.setObjectName("actionSimulasi_Tabungan_Berjangka")
        self.actionSimulasi_Anggaran_Bulanan = QtWidgets.QAction(MainWindow)
        self.actionSimulasi_Anggaran_Bulanan.setObjectName("actionSimulasi_Anggaran_Bulanan")
        self.actionSimulasi_Peminjaman = QtWidgets.QAction(MainWindow)
        self.actionSimulasi_Peminjaman.setObjectName("actionSimulasi_Peminjaman")
        self.menuMenu.addAction(self.actionSimulasi_Tabungan_Berjangka)
        self.menuMenu.addAction(self.actionSimulasi_Anggaran_Bulanan)
        self.menuMenu.addAction(self.actionSimulasi_Peminjaman)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.actionSimulasi_Tabungan_Berjangka.triggered.connect(Simulasi_Tabungan_Berjangka)
        self.actionSimulasi_Anggaran_Bulanan.triggered.connect(Simulasi_Anggaran_Bulanan)
        self.actionSimulasi_Peminjaman.triggered.connect(Simulasi_Peminjaman)



    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ANDA MASUK KE MAIN WINDOW"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionSimulasi_Tabungan_Berjangka.setText(_translate("MainWindow", "Simulasi Tabungan Berjangka"))
        self.actionSimulasi_Anggaran_Bulanan.setText(_translate("MainWindow", "Simulasi Anggaran Bulanan"))
        self.actionSimulasi_Peminjaman.setText(_translate("MainWindow", "Simulasi Peminjaman"))

#membuat fungsi Simulasi_Tabungan_Berjangka
def Simulasi_Tabungan_Berjangka():
    #memanggil/menampilkan aplikasi Simulasi_Tabungan_Berjangka
    tabungan_berjangka.Layout()
#membuat fungsi Simulasi_Anggaran_Bulanan
def Simulasi_Anggaran_Bulanan():
    #memanggil/menampilkan aplikasi Simulasi_Anggaran_Bulanan
    anggaran_bulanan.Layout()
#membuat fungsi Simulasi_Peminjaman
def Simulasi_Peminjaman():
    #memanggil/menampilkan aplikasi Simulasi_Peminjaman
    simulasi_peminjaman.Layout()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
