# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator_Fix.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(410, 327)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 381, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.pushBack = QtWidgets.QPushButton(Form)
        self.pushBack.setGeometry(QtCore.QRect(10, 70, 121, 41))
        self.pushBack.setObjectName("pushBack")
        self.pushCE = QtWidgets.QPushButton(Form)
        self.pushCE.setGeometry(QtCore.QRect(150, 70, 111, 41))
        self.pushCE.setObjectName("pushCE")
        self.pushC = QtWidgets.QPushButton(Form)
        self.pushC.setGeometry(QtCore.QRect(280, 70, 111, 41))
        self.pushC.setObjectName("pushC")
        self.push7 = QtWidgets.QPushButton(Form)
        self.push7.setGeometry(QtCore.QRect(10, 120, 61, 41))
        self.push7.setObjectName("push7")
        self.push4 = QtWidgets.QPushButton(Form)
        self.push4.setGeometry(QtCore.QRect(10, 170, 61, 41))
        self.push4.setObjectName("push4")
        self.push1 = QtWidgets.QPushButton(Form)
        self.push1.setGeometry(QtCore.QRect(10, 220, 61, 41))
        self.push1.setObjectName("push1")
        self.push0 = QtWidgets.QPushButton(Form)
        self.push0.setGeometry(QtCore.QRect(10, 270, 61, 41))
        self.push0.setObjectName("push0")
        self.push8 = QtWidgets.QPushButton(Form)
        self.push8.setGeometry(QtCore.QRect(90, 120, 61, 41))
        self.push8.setObjectName("push8")
        self.push5 = QtWidgets.QPushButton(Form)
        self.push5.setGeometry(QtCore.QRect(90, 170, 61, 41))
        self.push5.setObjectName("push5")
        self.push2 = QtWidgets.QPushButton(Form)
        self.push2.setGeometry(QtCore.QRect(90, 220, 61, 41))
        self.push2.setObjectName("push2")
        self.pushplusminus = QtWidgets.QPushButton(Form)
        self.pushplusminus.setGeometry(QtCore.QRect(90, 270, 61, 41))
        self.pushplusminus.setObjectName("pushplusminus")
        self.push9 = QtWidgets.QPushButton(Form)
        self.push9.setGeometry(QtCore.QRect(170, 120, 61, 41))
        self.push9.setObjectName("push9")
        self.push6 = QtWidgets.QPushButton(Form)
        self.push6.setGeometry(QtCore.QRect(170, 170, 61, 41))
        self.push6.setObjectName("push6")
        self.push3 = QtWidgets.QPushButton(Form)
        self.push3.setGeometry(QtCore.QRect(170, 220, 61, 41))
        self.push3.setObjectName("push3")
        self.pushdot = QtWidgets.QPushButton(Form)
        self.pushdot.setGeometry(QtCore.QRect(170, 270, 61, 41))
        self.pushdot.setObjectName("pushdot")
        self.pushbagi = QtWidgets.QPushButton(Form)
        self.pushbagi.setGeometry(QtCore.QRect(250, 120, 61, 41))
        self.pushbagi.setObjectName("pushbagi")
        self.pushkali = QtWidgets.QPushButton(Form)
        self.pushkali.setGeometry(QtCore.QRect(250, 170, 61, 41))
        self.pushkali.setObjectName("pushkali")
        self.pushminus = QtWidgets.QPushButton(Form)
        self.pushminus.setGeometry(QtCore.QRect(250, 220, 61, 41))
        self.pushminus.setObjectName("pushminus")
        self.pushplus = QtWidgets.QPushButton(Form)
        self.pushplus.setGeometry(QtCore.QRect(250, 270, 61, 41))
        self.pushplus.setObjectName("pushplus")
        self.pushakar = QtWidgets.QPushButton(Form)
        self.pushakar.setGeometry(QtCore.QRect(330, 120, 61, 41))
        self.pushakar.setObjectName("pushakar")
        self.pushkuadrat = QtWidgets.QPushButton(Form)
        self.pushkuadrat.setGeometry(QtCore.QRect(330, 170, 61, 41))
        self.pushkuadrat.setObjectName("pushkuadrat")
        self.pushequal = QtWidgets.QPushButton(Form)
        self.pushequal.setGeometry(QtCore.QRect(330, 220, 61, 91))
        self.pushequal.setObjectName("pushequal")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.push1.clicked.connect(self.function1)
        self.push2.clicked.connect(self.function2)
        self.push3.clicked.connect(self.function3)
        self.push4.clicked.connect(self.function4)
        self.push5.clicked.connect(self.function5)
        self.push6.clicked.connect(self.function6)
        self.push7.clicked.connect(self.function7)
        self.push8.clicked.connect(self.function8)
        self.push9.clicked.connect(self.function9)
        self.push0.clicked.connect(self.function0)
        self.pushdot.clicked.connect(self.functionDot)
        self.pushplus.clicked.connect(self.functionPlus)
        self.pushminus.clicked.connect(self.functionMinus)
        self.pushplusminus.clicked.connect(self.functionPlusMinus)
        self.pushkali.clicked.connect(self.functionKali)
        self.pushbagi.clicked.connect(self.functionBagi)
        self.pushakar.clicked.connect(self.functionAkar)
        self.pushkuadrat.clicked.connect(self.functionKuadrat)
        self.pushequal.clicked.connect(self.functionEqual)
        self.pushC.clicked.connect(self.functionC)
        self.pushCE.clicked.connect(self.functionCE)
        self.pushBack.clicked.connect(self.functionBack)

    def function1(self):
        inputEdit = self.lineEdit.text()
        self.lineEdit.setText(inputEdit+"1")

    def function2(self):
        inputEdit = self.lineEdit.text()
        self.lineEdit.setText(inputEdit+"2")

    def function3(self):
        inputEdit = self.lineEdit.text()
        self.lineEdit.setText(inputEdit+"3")

    def function4(self):
        inputEdit = self.lineEdit.text()
        self.lineEdit.setText(inputEdit+"4")

    def function5(self):
        inputEdit = self.lineEdit.text()
        self.lineEdit.setText(inputEdit+"5")

    def function6(self):
        inputEdit = self.lineEdit.text()
        self.lineEdit.setText(inputEdit+"6")

    def function7(self):
        inputEdit = self.lineEdit.text()
        self.lineEdit.setText(inputEdit+"7")

    def function8(self):
        inputEdit = self.lineEdit.text()
        self.lineEdit.setText(inputEdit+"8")

    def function9(self):
        inputEdit = self.lineEdit.text()
        self.lineEdit.setText(inputEdit+"9")

    def function0(self):
        inputEdit = self.lineEdit.text()
        self.lineEdit.setText(inputEdit+"0")

    def functionDot(self):
        inputEdit = self.lineEdit.text()
        self.lineEdit.setText(inputEdit+".")

    def functionPlus(self):
        inputEdit = self.lineEdit.text()
        self.lineEdit.setText(inputEdit+"+")

    def functionMinus(self):
        inputEdit = self.lineEdit.text()
        self.lineEdit.setText(inputEdit+"-")

    def functionPlusMinus(self):
        inputEdit = self.lineEdit.text()        
        self.lineEdit.setText("-"+inputEdit)

    def functionKali(self):
        inputEdit = self.lineEdit.text()
        self.lineEdit.setText(inputEdit+"*")

    def functionBagi(self):
        inputEdit = self.lineEdit.text()
        self.lineEdit.setText(inputEdit+"/")

    def functionAkar(self):
        inputEdit = self.lineEdit.text()
        hasil = int(inputEdit) ** (0.5)
        self.lineEdit.setText(str(hasil))

    def functionKuadrat(self):
        inputEdit = int(self.lineEdit.text())
        hasil = inputEdit * inputEdit
        self.lineEdit.setText(str(hasil))
        #self.lineEdit.setText(inputEdit+"²")

    def functionC(self):
        self.lineEdit.setText("")

    def functionCE(self):
        self.lineEdit.setText("")

    def functionBack(self):
        inputEdit = self.lineEdit.text()
        self.lineEdit.setText(inputEdit[:len(inputEdit)-1])

    def functionEqual(self):
        inputEdit = self.lineEdit.text()
        try:
            hasil = eval(inputEdit)
            self.lineEdit.setText(str(hasil))
        except:
            self.lineEdit.setText("INVALID")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculator"))
        self.pushBack.setText(_translate("Form", "Back"))
        self.pushCE.setText(_translate("Form", "CE"))
        self.pushC.setText(_translate("Form", "C"))
        self.push7.setText(_translate("Form", "7"))
        self.push4.setText(_translate("Form", "4"))
        self.push1.setText(_translate("Form", "1"))
        self.push0.setText(_translate("Form", "0"))
        self.push8.setText(_translate("Form", "8"))
        self.push5.setText(_translate("Form", "5"))
        self.push2.setText(_translate("Form", "2"))
        self.pushplusminus.setText(_translate("Form", "+/-"))
        self.push9.setText(_translate("Form", "9"))
        self.push6.setText(_translate("Form", "6"))
        self.push3.setText(_translate("Form", "3"))
        self.pushdot.setText(_translate("Form", "."))
        self.pushbagi.setText(_translate("Form", "/"))
        self.pushkali.setText(_translate("Form", "*"))
        self.pushminus.setText(_translate("Form", "-"))
        self.pushplus.setText(_translate("Form", "+"))
        self.pushakar.setText(_translate("Form", "√"))
        self.pushkuadrat.setText(_translate("Form", "x²"))
        self.pushequal.setText(_translate("Form", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
